COMPONENT=MotionOscAppC
CFLAGS += -I$(TOSDIR)/lib/printf

CFLAGS += -I../../../common
CFLAGS += -I../../../common/transceiver
CFLAGS += -I../../platform/lsm303
CFLAGS += -I../../platform/PIR
CFLAGS += -I../../platform/CO2

include $(MAKERULES)
